services:
  docs:
    image: nginx:alpine
    container_name: ils-docs
    restart: always
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./deploy:/etc/nginx/conf.d:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
