server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~ /\.(git|github) { deny all; return 404; }
    location = /docker-compose.yml { deny all; return 404; }
    location ^~ /deploy/ { deny all; return 404; }

    location /assets/ {
        expires 7d;
        add_header Cache-Control "public";
    }

    error_page 404 /404.html;
}
